Repository usd-cs/comp495-sp18-happy-hour, pull requests merged in 2018-05, with the labels that each got.

#125 Resolved #122, Fixed Favorites Persistence
  Cheers/Controller/ListViewController.swift
  Cheers/Model/Singletons/FavoritesSingleton.swift
Labels: bug

#126 Resolves #122 and adds favorites only filter functionality
  Cheers/Controller/ListViewController.swift
  Cheers/Controller/MapViewController.swift
  Cheers/Model/Singletons/FavoritesSingleton.swift
  Cheers/Model/Singletons/SharedListsSingleton.swift
Labels: bug

#127 Resolves #123, Sort Filter Added
  Cheers.xcodeproj/project.pbxproj
  Cheers/Controller/Filter Classes/FilterMenu.swift
  Cheers/Controller/Filter Classes/SortFilterOptionCell.swift
  Cheers/Model/Singletons/FilterSettingsSingleton.swift
  Cheers/Model/Singletons/SharedListsSingleton.swift
Labels: core functionality, enhancement

#136 Update README.md
  README.md
Labels: bug

#137 Added happy hours to database
  Cheers.xcodeproj/xcuserdata/maevemcclatchey.xcuserdatad/xcschemes/xcschememanagement.plist
  Cheers/Neighborhoods.swift
  Cheers/records.txt
Labels: database
